language: c++
compiler: gcc

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET="linux64"

    - os: osx
      osx_image: xcode8
      env: TARGET="osx"

before_install:
  - if [ "$TARGET" == "linux64" ]; then
      sudo apt-get update;
    fi

  - if [ "$TARGET" == "osx" ]; then
      brew update;
    fi

install:
  - if [ "$TARGET" == "linux64" ]; then
      sudo apt-get install qt5-default qttools5-dev-tools;
      sudo apt-get install liblo-dev liblo-tools;
      sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-vaapi gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-x gstreamer1.0-tools;
      sudo apt-get install qtmultimedia5-dev;
    fi

  - if [ "$TARGET" == "osx" ]; then
      brew install qt;
      brew install liblo;
      brew install gstreamer gst-plugins-bad gst-plugins-base gst-plugins-good gst-libav;
    fi

script:
  - qmake mapmap.pro
  - make
